export const HOME_SCREEN_DETAIL_REQUEST = 'HOME_SCREEN_DETAIL_REQUEST'
export const HOME_SCREEN_DETAIL_SUCCESS = 'HOME_SCREEN_DETAIL_SUCCESS'
export const HOME_SCREEN_DETAIL_FAIL = 'HOME_SCREEN_DETAIL_FAIL'